import { House } from './house';

export const HOUSES: House[] = [
  {
    name: 'Pod Lipką',
    imagePath: 'pod-lipka',
    rooms: 3,
    bathrooms: 1,
    minWidth: 20,
    minLength: 17,
    workRoom: false,
    design: false,
    garage: 0,
    handicapped: true
  },
  {
    name: 'W Borówkach',
    imagePath: 'w-borowkach',
    rooms: 3,
    bathrooms: 1,
    minWidth: 15,
    minLength: 16,
    workRoom: false,
    design: true,
    garage: 0,
    handicapped: false
  },
  {
    name: 'W Pięknotkach',
    imagePath: 'w-pieknotkach',
    rooms: 3,
    bathrooms: 1,
    minWidth: 18,
    minLength: 17,
    workRoom: true,
    design: false,
    garage: 1,
    handicapped: false
  },
  {
    name: 'Pod Graviolą',
    imagePath: 'pod-graviola',
    rooms: 3,
    bathrooms: 1,
    minWidth: 18,
    minLength: 18,
    workRoom: true,
    design: true,
    garage: 0,
    handicapped: false
  },
  {
    name: 'W Galach',
    imagePath: 'w-galach',
    rooms: 4,
    bathrooms: 2,
    minWidth: 22,
    minLength: 24,
    workRoom: true,
    design: true,
    garage: 0,
    handicapped: true
  },
  {
    name: 'W Rododendronach',
    imagePath: 'w-rododendronach',
    rooms: 5,
    bathrooms: 2,
    minWidth: 17,
    minLength: 17,
    workRoom: false,
    design: false,
    garage: 0,
    handicapped: false
  },
  {
    name: 'W Morelach',
    imagePath: 'w-morelach',
    rooms: 5,
    bathrooms: 2,
    minWidth: 20,
    minLength: 19,
    workRoom: true,
    design: false,
    garage: 1,
    handicapped: false
  },
  {
    name: 'W Laurach',
    imagePath: 'w-laurach',
    rooms: 4,
    bathrooms: 2,
    minWidth: 27,
    minLength: 16,
    workRoom: true,
    design: true,
    garage: 1,
    handicapped: false
  },
  {
    name: 'W Kliwiach',
    imagePath: 'w-kliwiach',
    rooms: 5,
    bathrooms: 1,
    minWidth: 30,
    minLength: 31,
    workRoom: true,
    design: false,
    garage: 2,
    handicapped: true
  },
  {
    name: 'Eliza 3',
    imagePath: 'eliza',
    rooms: 5,
    bathrooms: 3,
    minWidth: 27,
    minLength: 22,
    workRoom: true,
    design: true,
    garage: 2,
    handicapped: false
  },
  {
    name: 'W Kalateach',
    imagePath: 'w-kalateach',
    rooms: 5,
    bathrooms: 3,
    minWidth: 24,
    minLength: 23,
    workRoom: true,
    design: false,
    garage: 2,
    handicapped: false
  },
  {
    name: 'W Karaganach',
    imagePath: 'w-karaganach',
    rooms: 4,
    bathrooms: 3,
    minWidth: 27,
    minLength: 17,
    workRoom: true,
    design: true,
    garage: 0,
    handicapped: false
  },
]